package org.aspose.slides.foss;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Tests for the {@link ShapeType} enum.
 *
 * <p>Verifies that all expected enum constants are present and OOXML mappings work correctly.</p>
 */
class ShapeTypeTest {

    @Test
    void allEnumConstants_exist() {
        // Verify all expected ShapeType enum constants are present
        assertThat(ShapeType.NOT_DEFINED).isNotNull();
        assertThat(ShapeType.CUSTOM).isNotNull();
        assertThat(ShapeType.LINE).isNotNull();
        assertThat(ShapeType.LINE_INVERSE).isNotNull();
        assertThat(ShapeType.TRIANGLE).isNotNull();
        assertThat(ShapeType.RIGHT_TRIANGLE).isNotNull();
        assertThat(ShapeType.RECTANGLE).isNotNull();
        assertThat(ShapeType.DIAMOND).isNotNull();
        assertThat(ShapeType.PARALLELOGRAM).isNotNull();
        assertThat(ShapeType.TRAPEZOID).isNotNull();
        assertThat(ShapeType.NON_ISOSCELES_TRAPEZOID).isNotNull();
        assertThat(ShapeType.PENTAGON).isNotNull();
        assertThat(ShapeType.HEXAGON).isNotNull();
        assertThat(ShapeType.HEPTAGON).isNotNull();
        assertThat(ShapeType.OCTAGON).isNotNull();
        assertThat(ShapeType.DECAGON).isNotNull();
        assertThat(ShapeType.DODECAGON).isNotNull();
        assertThat(ShapeType.FOUR_POINTED_STAR).isNotNull();
        assertThat(ShapeType.FIVE_POINTED_STAR).isNotNull();
        assertThat(ShapeType.SIX_POINTED_STAR).isNotNull();
        assertThat(ShapeType.SEVEN_POINTED_STAR).isNotNull();
        assertThat(ShapeType.EIGHT_POINTED_STAR).isNotNull();
        assertThat(ShapeType.TEN_POINTED_STAR).isNotNull();
        assertThat(ShapeType.TWELVE_POINTED_STAR).isNotNull();
        assertThat(ShapeType.SIXTEEN_POINTED_STAR).isNotNull();
        assertThat(ShapeType.TWENTY_FOUR_POINTED_STAR).isNotNull();
        assertThat(ShapeType.THIRTY_TWO_POINTED_STAR).isNotNull();
        assertThat(ShapeType.ROUND_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.ONE_ROUND_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.TWO_SAMESIDE_ROUND_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.TWO_DIAGONAL_ROUND_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.ONE_SNIP_ONE_ROUND_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.ONE_SNIP_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.TWO_SAMESIDE_SNIP_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.TWO_DIAGONAL_SNIP_CORNER_RECTANGLE).isNotNull();
        assertThat(ShapeType.PLAQUE).isNotNull();
        assertThat(ShapeType.ELLIPSE).isNotNull();
        assertThat(ShapeType.TEARDROP).isNotNull();
        assertThat(ShapeType.HOME_PLATE).isNotNull();
        assertThat(ShapeType.CHEVRON).isNotNull();
        assertThat(ShapeType.PIE_WEDGE).isNotNull();
        assertThat(ShapeType.PIE).isNotNull();
        assertThat(ShapeType.BLOCK_ARC).isNotNull();
        assertThat(ShapeType.DONUT).isNotNull();
        assertThat(ShapeType.NO_SMOKING).isNotNull();
        assertThat(ShapeType.RIGHT_ARROW).isNotNull();
        assertThat(ShapeType.LEFT_ARROW).isNotNull();
        assertThat(ShapeType.UP_ARROW).isNotNull();
        assertThat(ShapeType.DOWN_ARROW).isNotNull();
        assertThat(ShapeType.STRIPED_RIGHT_ARROW).isNotNull();
        assertThat(ShapeType.NOTCHED_RIGHT_ARROW).isNotNull();
        assertThat(ShapeType.BENT_UP_ARROW).isNotNull();
        assertThat(ShapeType.LEFT_RIGHT_ARROW).isNotNull();
        assertThat(ShapeType.UP_DOWN_ARROW).isNotNull();
        assertThat(ShapeType.LEFT_UP_ARROW).isNotNull();
        assertThat(ShapeType.LEFT_RIGHT_UP_ARROW).isNotNull();
        assertThat(ShapeType.QUAD_ARROW).isNotNull();
        assertThat(ShapeType.CALLOUT_LEFT_ARROW).isNotNull();
        assertThat(ShapeType.CALLOUT_RIGHT_ARROW).isNotNull();
        assertThat(ShapeType.CALLOUT_UP_ARROW).isNotNull();
        assertThat(ShapeType.CALLOUT_DOWN_ARROW).isNotNull();
        assertThat(ShapeType.CALLOUT_LEFT_RIGHT_ARROW).isNotNull();
        assertThat(ShapeType.CALLOUT_UP_DOWN_ARROW).isNotNull();
        assertThat(ShapeType.CALLOUT_QUAD_ARROW).isNotNull();
        assertThat(ShapeType.BENT_ARROW).isNotNull();
        assertThat(ShapeType.U_TURN_ARROW).isNotNull();
        assertThat(ShapeType.CIRCULAR_ARROW).isNotNull();
        assertThat(ShapeType.LEFT_CIRCULAR_ARROW).isNotNull();
        assertThat(ShapeType.LEFT_RIGHT_CIRCULAR_ARROW).isNotNull();
        assertThat(ShapeType.CURVED_RIGHT_ARROW).isNotNull();
        assertThat(ShapeType.CURVED_LEFT_ARROW).isNotNull();
        assertThat(ShapeType.CURVED_UP_ARROW).isNotNull();
        assertThat(ShapeType.CURVED_DOWN_ARROW).isNotNull();
        assertThat(ShapeType.SWOOSH_ARROW).isNotNull();
        assertThat(ShapeType.CUBE).isNotNull();
        assertThat(ShapeType.CAN).isNotNull();
        assertThat(ShapeType.LIGHTNING_BOLT).isNotNull();
        assertThat(ShapeType.HEART).isNotNull();
        assertThat(ShapeType.SUN).isNotNull();
        assertThat(ShapeType.MOON).isNotNull();
        assertThat(ShapeType.SMILEY_FACE).isNotNull();
        assertThat(ShapeType.IRREGULAR_SEAL1).isNotNull();
        assertThat(ShapeType.IRREGULAR_SEAL2).isNotNull();
        assertThat(ShapeType.FOLDED_CORNER).isNotNull();
        assertThat(ShapeType.BEVEL).isNotNull();
        assertThat(ShapeType.FRAME).isNotNull();
        assertThat(ShapeType.HALF_FRAME).isNotNull();
        assertThat(ShapeType.CORNER).isNotNull();
        assertThat(ShapeType.DIAGONAL_STRIPE).isNotNull();
        assertThat(ShapeType.CHORD).isNotNull();
        assertThat(ShapeType.CURVED_ARC).isNotNull();
        assertThat(ShapeType.LEFT_BRACKET).isNotNull();
        assertThat(ShapeType.RIGHT_BRACKET).isNotNull();
        assertThat(ShapeType.LEFT_BRACE).isNotNull();
        assertThat(ShapeType.RIGHT_BRACE).isNotNull();
        assertThat(ShapeType.BRACKET_PAIR).isNotNull();
        assertThat(ShapeType.BRACE_PAIR).isNotNull();
        assertThat(ShapeType.STRAIGHT_CONNECTOR1).isNotNull();
        assertThat(ShapeType.BENT_CONNECTOR2).isNotNull();
        assertThat(ShapeType.BENT_CONNECTOR3).isNotNull();
        assertThat(ShapeType.BENT_CONNECTOR4).isNotNull();
        assertThat(ShapeType.BENT_CONNECTOR5).isNotNull();
        assertThat(ShapeType.CURVED_CONNECTOR2).isNotNull();
        assertThat(ShapeType.CURVED_CONNECTOR3).isNotNull();
        assertThat(ShapeType.CURVED_CONNECTOR4).isNotNull();
        assertThat(ShapeType.CURVED_CONNECTOR5).isNotNull();
        assertThat(ShapeType.CALLOUT1).isNotNull();
        assertThat(ShapeType.CALLOUT2).isNotNull();
        assertThat(ShapeType.CALLOUT3).isNotNull();
        assertThat(ShapeType.CALLOUT_1_WITH_ACCENT).isNotNull();
        assertThat(ShapeType.CALLOUT_2_WITH_ACCENT).isNotNull();
        assertThat(ShapeType.CALLOUT_3_WITH_ACCENT).isNotNull();
        assertThat(ShapeType.CALLOUT_1_WITH_BORDER).isNotNull();
        assertThat(ShapeType.CALLOUT_2_WITH_BORDER).isNotNull();
        assertThat(ShapeType.CALLOUT_3_WITH_BORDER).isNotNull();
        assertThat(ShapeType.CALLOUT_1_WITH_BORDER_AND_ACCENT).isNotNull();
        assertThat(ShapeType.CALLOUT_2_WITH_BORDER_AND_ACCENT).isNotNull();
        assertThat(ShapeType.CALLOUT_3_WITH_BORDER_AND_ACCENT).isNotNull();
        assertThat(ShapeType.CALLOUT_WEDGE_RECTANGLE).isNotNull();
        assertThat(ShapeType.CALLOUT_WEDGE_ROUND_RECTANGLE).isNotNull();
        assertThat(ShapeType.CALLOUT_WEDGE_ELLIPSE).isNotNull();
        assertThat(ShapeType.CALLOUT_CLOUD).isNotNull();
        assertThat(ShapeType.CLOUD).isNotNull();
        assertThat(ShapeType.RIBBON).isNotNull();
        assertThat(ShapeType.RIBBON2).isNotNull();
        assertThat(ShapeType.ELLIPSE_RIBBON).isNotNull();
        assertThat(ShapeType.ELLIPSE_RIBBON2).isNotNull();
        assertThat(ShapeType.LEFT_RIGHT_RIBBON).isNotNull();
        assertThat(ShapeType.VERTICAL_SCROLL).isNotNull();
        assertThat(ShapeType.HORIZONTAL_SCROLL).isNotNull();
        assertThat(ShapeType.WAVE).isNotNull();
        assertThat(ShapeType.DOUBLE_WAVE).isNotNull();
        assertThat(ShapeType.PLUS).isNotNull();
        assertThat(ShapeType.PROCESS_FLOW).isNotNull();
        assertThat(ShapeType.DECISION_FLOW).isNotNull();
        assertThat(ShapeType.INPUT_OUTPUT_FLOW).isNotNull();
        assertThat(ShapeType.PREDEFINED_PROCESS_FLOW).isNotNull();
        assertThat(ShapeType.INTERNAL_STORAGE_FLOW).isNotNull();
        assertThat(ShapeType.DOCUMENT_FLOW).isNotNull();
        assertThat(ShapeType.MULTI_DOCUMENT_FLOW).isNotNull();
        assertThat(ShapeType.TERMINATOR_FLOW).isNotNull();
        assertThat(ShapeType.PREPARATION_FLOW).isNotNull();
        assertThat(ShapeType.MANUAL_INPUT_FLOW).isNotNull();
        assertThat(ShapeType.MANUAL_OPERATION_FLOW).isNotNull();
        assertThat(ShapeType.CONNECTOR_FLOW).isNotNull();
        assertThat(ShapeType.PUNCHED_CARD_FLOW).isNotNull();
        assertThat(ShapeType.PUNCHED_TAPE_FLOW).isNotNull();
        assertThat(ShapeType.SUMMING_JUNCTION_FLOW).isNotNull();
        assertThat(ShapeType.OR_FLOW).isNotNull();
        assertThat(ShapeType.COLLATE_FLOW).isNotNull();
        assertThat(ShapeType.SORT_FLOW).isNotNull();
        assertThat(ShapeType.EXTRACT_FLOW).isNotNull();
        assertThat(ShapeType.MERGE_FLOW).isNotNull();
        assertThat(ShapeType.OFFLINE_STORAGE_FLOW).isNotNull();
        assertThat(ShapeType.ONLINE_STORAGE_FLOW).isNotNull();
        assertThat(ShapeType.MAGNETIC_TAPE_FLOW).isNotNull();
        assertThat(ShapeType.MAGNETIC_DISK_FLOW).isNotNull();
        assertThat(ShapeType.MAGNETIC_DRUM_FLOW).isNotNull();
        assertThat(ShapeType.DISPLAY_FLOW).isNotNull();
        assertThat(ShapeType.DELAY_FLOW).isNotNull();
        assertThat(ShapeType.ALTERNATE_PROCESS_FLOW).isNotNull();
        assertThat(ShapeType.OFF_PAGE_CONNECTOR_FLOW).isNotNull();
        assertThat(ShapeType.BLANK_BUTTON).isNotNull();
        assertThat(ShapeType.HOME_BUTTON).isNotNull();
        assertThat(ShapeType.HELP_BUTTON).isNotNull();
        assertThat(ShapeType.INFORMATION_BUTTON).isNotNull();
        assertThat(ShapeType.FORWARD_OR_NEXT_BUTTON).isNotNull();
        assertThat(ShapeType.BACK_OR_PREVIOUS_BUTTON).isNotNull();
        assertThat(ShapeType.END_BUTTON).isNotNull();
        assertThat(ShapeType.BEGINNING_BUTTON).isNotNull();
        assertThat(ShapeType.RETURN_BUTTON).isNotNull();
        assertThat(ShapeType.DOCUMENT_BUTTON).isNotNull();
        assertThat(ShapeType.SOUND_BUTTON).isNotNull();
        assertThat(ShapeType.MOVIE_BUTTON).isNotNull();
        assertThat(ShapeType.GEAR6).isNotNull();
        assertThat(ShapeType.GEAR9).isNotNull();
        assertThat(ShapeType.FUNNEL).isNotNull();
        assertThat(ShapeType.PLUS_MATH).isNotNull();
        assertThat(ShapeType.MINUS_MATH).isNotNull();
        assertThat(ShapeType.MULTIPLY_MATH).isNotNull();
        assertThat(ShapeType.DIVIDE_MATH).isNotNull();
        assertThat(ShapeType.EQUAL_MATH).isNotNull();
        assertThat(ShapeType.NOT_EQUAL_MATH).isNotNull();
        assertThat(ShapeType.CORNER_TABS).isNotNull();
        assertThat(ShapeType.SQUARE_TABS).isNotNull();
        assertThat(ShapeType.PLAQUE_TABS).isNotNull();
        assertThat(ShapeType.CHART_X).isNotNull();
        assertThat(ShapeType.CHART_STAR).isNotNull();
        assertThat(ShapeType.CHART_PLUS).isNotNull();
    }

    @Test
    void fromOoxml_resolvesKnownPresets() {
        assertThat(ShapeType.fromOoxml("rect")).contains(ShapeType.RECTANGLE);
        assertThat(ShapeType.fromOoxml("ellipse")).contains(ShapeType.ELLIPSE);
        assertThat(ShapeType.fromOoxml("straightConnector1")).contains(ShapeType.STRAIGHT_CONNECTOR1);
        assertThat(ShapeType.fromOoxml("bentConnector3")).contains(ShapeType.BENT_CONNECTOR3);
        assertThat(ShapeType.fromOoxml("roundRect")).contains(ShapeType.ROUND_CORNER_RECTANGLE);
        assertThat(ShapeType.fromOoxml("star5")).contains(ShapeType.FIVE_POINTED_STAR);
        assertThat(ShapeType.fromOoxml("heart")).contains(ShapeType.HEART);
        assertThat(ShapeType.fromOoxml("flowChartProcess")).contains(ShapeType.PROCESS_FLOW);
        assertThat(ShapeType.fromOoxml("actionButtonHome")).contains(ShapeType.HOME_BUTTON);
    }

    @Test
    void fromOoxml_returnsEmptyForUnknown() {
        assertThat(ShapeType.fromOoxml("unknownShape")).isEmpty();
    }

    @Test
    void toOoxml_roundTripsForMappedTypes() {
        assertThat(ShapeType.RECTANGLE.toOoxml()).contains("rect");
        assertThat(ShapeType.ELLIPSE.toOoxml()).contains("ellipse");
        assertThat(ShapeType.STRAIGHT_CONNECTOR1.toOoxml()).contains("straightConnector1");
        assertThat(ShapeType.BENT_CONNECTOR3.toOoxml()).contains("bentConnector3");
        assertThat(ShapeType.HEART.toOoxml()).contains("heart");
        assertThat(ShapeType.PROCESS_FLOW.toOoxml()).contains("flowChartProcess");
    }

    @Test
    void toOoxml_returnsEmptyForNotDefined() {
        assertThat(ShapeType.NOT_DEFINED.toOoxml()).isEmpty();
    }

    @Test
    void toOoxml_returnsEmptyForCustom() {
        assertThat(ShapeType.CUSTOM.toOoxml()).isEmpty();
    }

    @Test
    void connectorShapeTypes_haveOoxmlMappings() {
        assertThat(ShapeType.STRAIGHT_CONNECTOR1.toOoxml()).isPresent();
        assertThat(ShapeType.BENT_CONNECTOR2.toOoxml()).isPresent();
        assertThat(ShapeType.BENT_CONNECTOR3.toOoxml()).isPresent();
        assertThat(ShapeType.BENT_CONNECTOR4.toOoxml()).isPresent();
        assertThat(ShapeType.BENT_CONNECTOR5.toOoxml()).isPresent();
        assertThat(ShapeType.CURVED_CONNECTOR2.toOoxml()).isPresent();
        assertThat(ShapeType.CURVED_CONNECTOR3.toOoxml()).isPresent();
        assertThat(ShapeType.CURVED_CONNECTOR4.toOoxml()).isPresent();
        assertThat(ShapeType.CURVED_CONNECTOR5.toOoxml()).isPresent();
    }
}
