package org.aspose.slides.foss.internal.opc;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Optional;

import static org.assertj.core.api.Assertions.assertThat;

class RelationshipsManagerTest {

    private OpcPackage pkg;

    @BeforeEach
    void setUp() {
        pkg = OpcPackage.createNew();
    }

    @Test
    void getRelsPartNameForRootReturnsRelsSlashDotRels() {
        assertThat(RelationshipsManager.getRelsPartName("")).isEqualTo("_rels/.rels");
    }

    @Test
    void getRelsPartNameForNestedPart() {
        assertThat(RelationshipsManager.getRelsPartName("ppt/presentation.xml"))
                .isEqualTo("ppt/_rels/presentation.xml.rels");
    }

    @Test
    void getRelsPartNameForDeeplyNestedPart() {
        assertThat(RelationshipsManager.getRelsPartName("ppt/slides/slide1.xml"))
                .isEqualTo("ppt/slides/_rels/slide1.xml.rels");
    }

    @Test
    void getRelsPartNameForFileWithoutDirectory() {
        assertThat(RelationshipsManager.getRelsPartName("content.xml"))
                .isEqualTo("_rels/content.xml.rels");
    }

    @Test
    void emptyPackageHasNoRelationships() {
        var mgr = new RelationshipsManager(pkg);
        assertThat(mgr.getAllRelationships()).isEmpty();
    }

    @Test
    void addRelationshipReturnsAutoGeneratedId() {
        var mgr = new RelationshipsManager(pkg);
        String id = mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("office_document"),
                "ppt/presentation.xml");
        assertThat(id).isEqualTo("rId1");
    }

    @Test
    void addRelationshipWithExplicitId() {
        var mgr = new RelationshipsManager(pkg);
        String id = mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("slide"),
                "slides/slide1.xml",
                "rId5",
                null);
        assertThat(id).isEqualTo("rId5");
    }

    @Test
    void getRelationshipReturnsAddedRelationship() {
        var mgr = new RelationshipsManager(pkg);
        mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("office_document"),
                "ppt/presentation.xml",
                "rId1",
                null);

        Optional<Relationship> rel = mgr.getRelationship("rId1");
        assertThat(rel).isPresent();
        assertThat(rel.get().id()).isEqualTo("rId1");
        assertThat(rel.get().type()).isEqualTo(
                RelationshipsManager.REL_TYPES.get("office_document"));
        assertThat(rel.get().target()).isEqualTo("ppt/presentation.xml");
        assertThat(rel.get().targetMode()).isEmpty();
    }

    @Test
    void getRelationshipReturnEmptyForMissing() {
        var mgr = new RelationshipsManager(pkg);
        assertThat(mgr.getRelationship("rId999")).isEmpty();
    }

    @Test
    void getRelationshipsByTypeFiltersCorrectly() {
        var mgr = new RelationshipsManager(pkg);
        String slideType = RelationshipsManager.REL_TYPES.get("slide");
        String themeType = RelationshipsManager.REL_TYPES.get("theme");

        mgr.addRelationship(slideType, "slides/slide1.xml");
        mgr.addRelationship(themeType, "theme/theme1.xml");
        mgr.addRelationship(slideType, "slides/slide2.xml");

        List<Relationship> slides = mgr.getRelationshipsByType(slideType);
        assertThat(slides).hasSize(2);
        assertThat(slides).allMatch(r -> r.type().equals(slideType));
    }

    @Test
    void addRelationshipWithExternalTargetMode() {
        var mgr = new RelationshipsManager(pkg);
        String id = mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("hyperlink"),
                "https://example.com",
                null,
                "External");

        Optional<Relationship> rel = mgr.getRelationship(id);
        assertThat(rel).isPresent();
        assertThat(rel.get().targetMode()).hasValue("External");
    }

    @Test
    void removeRelationshipReturnsTrueWhenFound() {
        var mgr = new RelationshipsManager(pkg);
        mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("slide"),
                "slides/slide1.xml",
                "rId1",
                null);

        assertThat(mgr.removeRelationship("rId1")).isTrue();
        assertThat(mgr.getRelationship("rId1")).isEmpty();
        assertThat(mgr.getAllRelationships()).isEmpty();
    }

    @Test
    void removeRelationshipReturnsFalseWhenNotFound() {
        var mgr = new RelationshipsManager(pkg);
        assertThat(mgr.removeRelationship("rId999")).isFalse();
    }

    @Test
    void generateRelIdSkipsExistingIds() {
        var mgr = new RelationshipsManager(pkg);
        mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("slide"),
                "slides/slide1.xml",
                "rId1",
                null);
        mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("slide"),
                "slides/slide2.xml",
                "rId2",
                null);

        // Next auto-generated should be rId3
        String id = mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("theme"),
                "theme/theme1.xml");
        assertThat(id).isEqualTo("rId3");
    }

    @Test
    void saveAndReloadPreservesRelationships() {
        var mgr = new RelationshipsManager(pkg);
        mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("office_document"),
                "ppt/presentation.xml",
                "rId1",
                null);
        mgr.addRelationship(
                RelationshipsManager.REL_TYPES.get("hyperlink"),
                "https://example.com",
                "rId2",
                "External");
        mgr.save();

        // Reload from the same package
        var mgr2 = new RelationshipsManager(pkg);
        assertThat(mgr2.getAllRelationships()).hasSize(2);

        Optional<Relationship> rel1 = mgr2.getRelationship("rId1");
        assertThat(rel1).isPresent();
        assertThat(rel1.get().target()).isEqualTo("ppt/presentation.xml");

        Optional<Relationship> rel2 = mgr2.getRelationship("rId2");
        assertThat(rel2).isPresent();
        assertThat(rel2.get().targetMode()).hasValue("External");
    }

    @Test
    void saveEmptyRelationshipsDeletesPart() {
        // Pre-populate a .rels file
        pkg.setPart("_rels/.rels", "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\"/>");

        var mgr = new RelationshipsManager(pkg);
        mgr.save();

        assertThat(pkg.hasPart("_rels/.rels")).isFalse();
    }

    @Test
    void partNameReturnsRelsPartName() {
        var mgr = new RelationshipsManager(pkg, "ppt/presentation.xml");
        assertThat(mgr.getPartName()).isEqualTo("ppt/_rels/presentation.xml.rels");
    }

    @Test
    void loadsExistingRelsFromPackage() {
        String xml = """
                <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
                <Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
                  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
                  <Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide1.xml"/>
                </Relationships>
                """;
        pkg.setPart("_rels/.rels", xml);

        var mgr = new RelationshipsManager(pkg);
        assertThat(mgr.getAllRelationships()).hasSize(2);
        assertThat(mgr.getRelationship("rId1")).isPresent();
        assertThat(mgr.getRelationship("rId2")).isPresent();
    }

    @Test
    void relTypesContainsExpectedEntries() {
        assertThat(RelationshipsManager.REL_TYPES).containsKey("office_document");
        assertThat(RelationshipsManager.REL_TYPES).containsKey("slide");
        assertThat(RelationshipsManager.REL_TYPES).containsKey("hyperlink");
        assertThat(RelationshipsManager.REL_TYPES).hasSize(20);
    }

    @Test
    void relsNamespaceConstant() {
        assertThat(RelationshipsManager.RELS_NAMESPACE)
                .isEqualTo("http://schemas.openxmlformats.org/package/2006/relationships");
    }

    @Test
    void relationshipRecordEquality() {
        var r1 = new Relationship("rId1", "type", "target", Optional.empty());
        var r2 = new Relationship("rId1", "type", "target");
        assertThat(r1).isEqualTo(r2);
    }
}
